"""Delivery Workbench PMO core.

Deterministic parser, validator, trace, and mutation primitives over the
Markdown roadmap under ``pm/roadmap/**``. This package is the single
source of behavior for ``bin/dw`` and any future adapter (workbench
server, gate engine). Markdown stays authoritative: nothing here caches
state outside the roadmap tree.
"""

from __future__ import annotations

from .model import (
    CUT_STATUSES,
    DONE_STATUSES,
    HOLD_STATUSES,
    OPEN_STATUSES,
    PARKED_STATUSES,
    PHASE_RE,
    STORY_ID_RE,
    STORY_RE,
    DwError,
    Phase,
    Project,
    StoryRow,
    die,
    normalize_status,
    status_note,
)
from .paths import (
    ensure_under,
    find_root,
    read_text,
    rel,
    roadmap_dir,
    slugify,
    strip_code,
    template_dir,
    work_log_root,
    write_text,
)
from .parse import (
    current_phase_status_path,
    discover_phases,
    discover_projects,
    find_story,
    get_phase,
    get_project,
    header_status,
    hook_snapshot,
    infer_prefix,
    link_target,
    parse_current_phase_target,
    parse_story_rows,
    phase_header_status,
    phase_is_paused,
    split_table_row,
    story_num_from_file,
    story_title,
    supplemental_canon,
)
from .trace import parse_work_log_entry, recent_commits, work_log_entries
from .render import (
    evidence_link_for,
    render_evidence,
    render_final_summary,
    render_phase_template,
    render_story_template,
    replace_phase_index_content,
    replace_story_table_content,
    update_current_phase_pointer_content,
    update_phase_index_status_content,
    update_story_header_status_content,
    update_story_table_row_content,
)
from .validate import check_project, project_warnings
from .mutations import (
    FileChange,
    MutationPlan,
    apply_plan,
    plan_fingerprint,
    plan_phase_close,
    plan_phase_advance,
    plan_phase_create,
    plan_phase_pause,
    plan_phase_resume,
    plan_story_create,
    plan_story_evidence,
    plan_story_status,
    preview_plan,
    projected_issues,
    write_changes,
)
from .board import BOARD_COLUMNS, board_bucket, board_model, render_board
from .api import (
    build_context_payload,
    handoff_summary,
    next_story,
    parked_headline,
    parked_lines,
    parked_summary,
    phase_events,
    project_context,
    story_context,
    story_detail,
    story_timeline,
)
from .contract import (
    apply_contract_certification,
    append_trailers,
    archive_contract,
    build_contract,
    contract_box_lines,
    contract_digest,
    contract_rule_titles,
    certify_contract_boxes,
    detect_story_ids,
    parse_contract_facts,
    rules_doc_path,
    write_contract,
)
from .evidence import (
    CAPTURE_HEADING_RE,
    TRUNCATION_MARKER,
    find_captured_run,
    latest_passing_capture,
    parse_captured_runs,
    render_capture_block,
    run_capture,
)
from .gate import (
    GateFailure,
    GateResult,
    render_gate_failure,
    render_gate_porcelain,
    run_gate,
)
from .verify import (
    VerifyResult,
    Violation,
    render_verify,
    render_verify_porcelain,
    run_verify,
)
from .model import EVIDENCE_PLACEHOLDER, STORY_STATUSES
from .validate import classify_issue, classify_warning, evidence_content_issues, health_report, hook_seam_explanations
from .agentdocs import (
    BEGIN_MARKER,
    END_MARKER,
    agent_docs_status,
    canonical_block,
    render_block,
    write_agent_docs,
)
from .doctor import DoctorCheck, render_doctor, run_doctor
from .adopt import AdoptionReport, parse_adoption_report, run_adoption
from .status import (
    STATUS_KIND,
    STATUS_SCHEMA_VERSION,
    build_status,
    render_status,
)
from .delivery_setup import (
    DELIVERY_SETUP_KIND,
    DELIVERY_SETUP_SCHEMA_VERSION,
    TECHNICAL_DETAILS_LABEL,
    build_delivery_setup,
    render_delivery_setup,
    render_delivery_setup_pointer,
)
from .step import (
    DEFAULT_STEP_OUTPUT_BYTES,
    STEP_KIND,
    STEP_RESULT_KIND,
    STEP_RESULT_SCHEMA_VERSION,
    STEP_SCHEMA_VERSION,
    StepChild,
    apply_step,
    build_step,
    render_step,
)
from .orchestration import (
    BUILTIN_CHECKS,
    CAPABILITIES,
    COMPILED_SCORE_KIND,
    NODE_TYPES,
    OUTPUT_FORMATS,
    ROLE_PRESETS,
    SCORE_KIND,
    SCORE_SCHEMA_VERSION,
    SIMULATION_KIND,
    TERMINALS,
    VALIDATION_KIND,
    WORKSPACE_MODES,
    OrchestrationValidationError,
    canonical_json,
    compile_score,
    compile_score_path,
    discover_score_paths,
    find_score_path,
    load_score,
    orchestration_dir,
    parse_score_text,
    score_inventory,
    simulate_score,
    validate_score,
)
from .programs import (
    BLOCKED_POLICIES,
    BUDGET_DEFAULTS as PROGRAM_BUDGET_DEFAULTS,
    COMPILED_KIND as COMPILED_PROGRAM_KIND,
    DUTIES as PROGRAM_DUTIES,
    INVENTORY_KIND as PROGRAM_INVENTORY_KIND,
    MODE_CEILINGS as PROGRAM_MODE_CEILINGS,
    ORGANIZATION_KIND,
    PLAN_KIND as PROGRAM_PLAN_KIND,
    PROGRAM_CAPABILITIES,
    PROGRAM_KIND,
    PROGRAM_SCHEMA_VERSION,
    RUBRIC_KIND,
    SELECTION_POLICIES as PROGRAM_SELECTION_POLICIES,
    SIMULATION_KIND as PROGRAM_SIMULATION_KIND,
    STOP_CONDITIONS as PROGRAM_STOP_CONDITIONS,
    VALIDATION_KIND as PROGRAM_VALIDATION_KIND,
    WORKFLOW_KIND,
    ProgramValidationError,
    build_program_plan,
    compile_program,
    compile_program_path,
    discover_program_paths,
    find_program_path,
    load_program,
    parse_program_text,
    program_inventory,
    simulate_program,
    validate_program,
    validate_program_path,
)
from .program_workflow import (
    ARTIFACT_KINDS as WORKFLOW_ARTIFACT_KINDS,
    COMPILED_WORKFLOW_KIND,
    CONTEXT_TYPES as WORKFLOW_CONTEXT_TYPES,
    ENVELOPE_KEYS as WORKFLOW_ENVELOPE_KEYS,
    INVENTORY_KIND as WORKFLOW_INVENTORY_KIND,
    LOOP_PURPOSES,
    NODE_TYPES as PROGRAM_WORKFLOW_NODE_TYPES,
    PARAMETER_TYPES as WORKFLOW_PARAMETER_TYPES,
    SIMULATION_KIND as WORKFLOW_SIMULATION_KIND,
    VALIDATION_KIND as WORKFLOW_VALIDATION_KIND,
    WORKFLOW_KIND as PROGRAM_WORKFLOW_KIND,
    WORKFLOW_SCHEMA_VERSION,
    WorkflowValidationError,
    compile_workflow,
    compile_workflow_path,
    discover_workflow_paths,
    find_workflow_path,
    load_workflow,
    parse_workflow_text,
    simulate_workflow,
    validate_workflow,
    workflow_inventory,
)
from .program_organization import (
    ASSIGNMENT_KIND as PROGRAM_ASSIGNMENT_KIND,
    COMPILED_ORGANIZATION_KIND,
    CONTEXT_CHANNELS as ORGANIZATION_CONTEXT_CHANNELS,
    DUTIES as ORGANIZATION_DUTIES,
    INVENTORY_KIND as ORGANIZATION_INVENTORY_KIND,
    ORGANIZATION_KIND as PROGRAM_ORGANIZATION_KIND,
    ORGANIZATION_SCHEMA_VERSION,
    REPLACEMENT_KIND as PROGRAM_REPLACEMENT_KIND,
    SIMULATION_KIND as ORGANIZATION_SIMULATION_KIND,
    VALIDATION_KIND as ORGANIZATION_VALIDATION_KIND,
    OrganizationValidationError,
    assign_organization_team,
    compile_organization,
    discover_organization_paths,
    find_organization_path,
    load_organization,
    organization_inventory,
    parse_organization_text,
    plan_assignment_replacement,
    simulate_organization,
    validate_organization,
    validate_workflow_team,
    workflow_role_requirements,
)
from .program_deliberation import (
    ARCHITECT_VERDICT_KIND,
    COUNCIL_DECISION_KIND,
    COUNCIL_VERDICT_KIND,
    DELIBERATION_EVENT_KIND,
    DELIBERATION_PLAN_KIND,
    DELIBERATION_PROJECTION_KIND,
    DELIBERATION_SCHEMA_VERSION,
    DELIBERATION_SIMULATION_KIND,
    META_VERDICT_KIND,
    OBLIGATION_KINDS,
    OBLIGATION_PRIORITIES,
    DeliberationError,
    claim_next_deliberation,
    compile_deliberation_plan,
    record_deliberation_replacement,
    record_deliberation_submission,
    replay_deliberation,
    simulate_deliberation,
    start_deliberation,
    validate_council_decision,
)
from .program_studio import (
    DELIVERY_CAPABILITIES as STUDIO_DELIVERY_CAPABILITIES,
    FAMILIES as PROGRAM_STUDIO_FAMILIES,
    STUDIO_AUTHORITY_KIND,
    STUDIO_DOCUMENT_KIND,
    STUDIO_GRAPH_KIND,
    STUDIO_KIND,
    STUDIO_MUTATION_PREVIEW_KIND,
    STUDIO_MUTATION_RESULT_KIND,
    STUDIO_ROUND_TRIP_KIND,
    STUDIO_SCHEMA_VERSION,
    WORK_AND_VERDICT_CAPABILITIES as STUDIO_WORK_AND_VERDICT_CAPABILITIES,
    StudioMutationPlan,
    apply_studio_mutation,
    build_authority_preview,
    build_program_studio,
    build_studio_document,
    build_studio_graph,
    build_studio_mutation_plan,
    graph_config_round_trip,
    new_studio_document,
    studio_graph_to_config,
    studio_mutation_preview,
)
from .program_verdict import (
    AGGREGATION_METHODS as VERDICT_AGGREGATION_METHODS,
    COMPILED_RUBRIC_KIND,
    CRITERION_RESULTS as VERDICT_CRITERION_RESULTS,
    EVIDENCE_KINDS as VERDICT_EVIDENCE_KINDS,
    FRESHNESS_BINDINGS as VERDICT_FRESHNESS_BINDINGS,
    GATE_REQUIREMENT_KINDS as QUALITY_GATE_REQUIREMENT_KINDS,
    GREEN_RESULTS as VERDICT_GREEN_RESULTS,
    MECHANICAL_FACT_KIND,
    MECHANICAL_PREDICATES,
    MECHANICAL_RECEIPT_KIND,
    META_AUDIT_MODES as VERDICT_META_AUDIT_MODES,
    QUALITY_GATE_KIND,
    QUALITY_PROOF_KIND,
    RED_RESULTS as VERDICT_RED_RESULTS,
    RUBRIC_INVENTORY_KIND,
    RUBRIC_SCHEMA_VERSION,
    RUBRIC_VALIDATION_KIND,
    SUBJECT_TYPES as VERDICT_SUBJECT_TYPES,
    TEAM_ASSIGNMENT_KIND as VERDICT_TEAM_ASSIGNMENT_KIND,
    VERDICT_ASSIGNMENT_KIND,
    VERDICT_KIND,
    VERDICT_RESULTS,
    VERDICT_SCHEMA_VERSION,
    VERDICT_TYPES,
    RubricValidationError,
    VerdictError,
    build_mechanical_fact,
    build_verdict_assignment,
    build_verdict_set_subject,
    compile_rubric,
    compose_panel_verdict,
    council_decision_freshness_issues,
    discover_rubric_paths,
    evaluate_quality_gate,
    find_rubric_path,
    issue_agent_verdict,
    load_rubric,
    normalize_subject as normalize_verdict_subject,
    parse_rubric_text,
    rubric_inventory,
    validate_mechanical_fact,
    validate_rubric,
    validate_verdict_document,
    verdict_freshness_issues,
)
from .program_run import (
    CONTROL_ACTIONS as PROGRAM_CONTROL_ACTIONS,
    PROGRAM_CHILD_GRANT_KIND,
    PROGRAM_CLAIM_PREVIEW_KIND,
    PROGRAM_COMPLETION_PREVIEW_KIND,
    PROGRAM_CONTROL_PREVIEW_KIND,
    PROGRAM_EVENT_KIND,
    PROGRAM_GRANT_KIND,
    PROGRAM_PERMANENT_EXCLUSIONS,
    PROGRAM_PROJECTION_KIND,
    PROGRAM_RUN_LIST_KIND,
    PROGRAM_RUN_SCHEMA_VERSION,
    PROGRAM_START_PLAN_KIND,
    PROGRAM_STATES,
    apply_program_claim,
    apply_program_completion,
    apply_program_control,
    build_program_claim_preview,
    build_program_completion_preview,
    build_program_control_preview,
    build_program_start_plan,
    complete_program_scope,
    derive_child_grant,
    dispose_program_obligation,
    program_freshness_issues,
    program_run_inventory,
    program_store_dir,
    record_program_dispatch,
    record_program_obligation,
    replay_program,
    start_program,
    validate_child_grant,
)
from .orchestration_edit import (
    SCORE_MUTATION_PREVIEW_KIND,
    SCORE_MUTATION_RESULT_KIND,
    SCORE_MUTATION_SCHEMA_VERSION,
    ScoreMutationPlan,
    apply_score_mutation,
    build_score_mutation_plan,
    score_mutation_preview,
)
from .orchestration_run import (
    MAX_GRANT_SECONDS,
    PERMANENT_EXCLUSIONS,
    RUN_EVENT_KIND,
    RUN_GRANT_KIND,
    RUN_KIND,
    RUN_PLAN_KIND,
    RUN_SCHEMA_VERSION,
    build_run_plan,
    claim_node,
    decide_checkpoint,
    decide_outstanding_request,
    maintain_outstanding_requests,
    observed_fact_binding,
    record_runtime_event,
    release_node_claim,
    replay_run,
    run_inventory,
    run_store_dir,
    start_run,
    transition_run,
)
from .orchestration_driver import (
    ARTIFACT_RECEIPT_KIND,
    DRIVER_CAPABILITY_KIND,
    DRIVER_CONFIG_KIND,
    DRIVER_RECEIPT_KIND,
    DRIVER_SCHEMA_VERSION,
    WORK_PACKET_KIND,
    ClaudeCodeExecDriver,
    CodexExecDriver,
    DriverManager,
    FixtureDriver,
    PiExecDriver,
    acquire_resource_groups,
    artifact_inventory,
    build_work_packet,
    driver_capability,
    driver_config_path,
    driver_inventory,
    load_driver_config,
    prepare_workspace,
    remove_workspace,
    validate_and_store_outputs,
    validate_driver_config,
    validate_work_packet,
    write_driver_config,
)
from .program_conductor import (
    PROGRAM_ARTIFACT_KIND,
    PROGRAM_CONDUCTOR_SCHEMA_VERSION,
    PROGRAM_DRIVER_OPERATION_KIND,
    PROGRAM_FRONTIER_KIND,
    PROGRAM_RECEIPT_KIND,
    PROGRAM_REQUEST_RESULT_KIND,
    PROGRAM_SUPERVISION_KIND,
    PROGRAM_TICK_KIND,
    ProgramDriverManager,
    ProgramFixtureDriver,
    derive_program_frontier,
    replay_program_conductor,
    respond_program_request,
    supervise_program,
    tick_program,
)
from .orchestration_conductor import (
    CHECK_RECEIPT_KIND,
    CONDUCTOR_DECISION_KIND,
    CONDUCTOR_SCHEMA_VERSION,
    CONDUCTOR_SUPERVISION_KIND,
    CONDUCTOR_TICK_KIND,
    RAIL_RECEIPT_KIND,
    CheckManager,
    RailManager,
    schedule_decision,
    supervise_run,
    tick_run,
)
from .orchestration_surface import (
    RUN_ACT_PREVIEW_KIND,
    RUN_STREAM_KIND,
    RUN_SUMMARY_KIND,
    RUN_SURFACE_SCHEMA_VERSION,
    RUN_VIEW_KIND,
    apply_run_act,
    build_run_act_preview,
    build_run_view,
    document_bytes,
    read_run_stream,
    run_summary_inventory,
    start_run_by_id,
    tail_run_events,
    tail_signal_events,
)
from .program_surface import (
    PROGRAM_ACT_PREVIEW_KIND,
    PROGRAM_STREAM_KIND as PROGRAM_SURFACE_STREAM_KIND,
    PROGRAM_SUMMARY_KIND as PROGRAM_SURFACE_SUMMARY_KIND,
    PROGRAM_SUPERVISION_SURFACE_KIND,
    PROGRAM_SURFACE_SCHEMA_VERSION,
    PROGRAM_TAIL_KIND as PROGRAM_SURFACE_TAIL_KIND,
    PROGRAM_TICK_SURFACE_KIND,
    PROGRAM_VIEW_KIND,
    apply_program_act,
    build_program_act_preview,
    build_program_view,
    document_bytes as program_document_bytes,
    program_summary_inventory,
    read_program_stream,
    start_program_by_id,
    tail_program_events,
)
from .signals import (
    NUDGE_INTENTS,
    SCM_NUDGE_SIGNALS,
    SIGNALS_KIND,
    SIGNALS_OBSERVE_KIND,
    SIGNAL_SCHEMA_VERSION,
    FixtureProvider,
    GithubProvider,
    build_signals_inventory,
    github_provider_for,
    latest_nudge_fact,
    observe_signals,
    parse_github_remote,
    receptivity,
    replay_channel,
    resolve_signal_channel,
)
from .notifications import (
    NOTIFICATIONS_KIND,
    NOTIFICATION_KINDS,
    acknowledge_notification,
    build_notifications,
    pending_deliveries,
    record_delivery,
    resolve_correlation,
)
from .orchestration_run import ACTIVITY_STATES

__version__ = "1.14.0"
